# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-27 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_oidc_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='verified'),
        ),
        migrations.AlterField(
            model_name='user',
            name='locale',
            field=models.CharField(choices=[('hr-HR', 'Croatian'), ('zh-CN', 'Chinese'), ('pl-PL', 'Polish'), ('fr-FR', 'French'), ('no-NO', 'Norwegian'), ('sl-SI', 'Slovenian'), ('ru-RU', 'Russian'), ('lv-LV', 'Latvian'), ('pt-PT', 'Portuguese'), ('nl-NL', 'Dutch'), ('de-DE', 'German'), ('fi-FI', 'Finnish'), ('da-DK', 'Danish'), ('es-ES', 'Spanish'), ('bg-BG', 'Bulgarian'), ('en-US', 'English'), ('sv-SE', 'Swedish'), ('hu-HU', 'Hungarian'), ('et-EE', 'Estonian'), ('lt-LT', 'Lithuanian'), ('it-IT', 'Italian'), ('ro-RO', 'Romanian'), ('cs-CZ', 'Czech'), ('tr-TR', 'Turkish'), ('el-GR', 'Greek'), ('sk-SK', 'Slovak')], default='en-US', max_length=254, verbose_name='locale'),
        ),
    ]
