# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-28 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_oidc_user', '0002_add_is_verified_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='locale',
            field=models.CharField(choices=[('bg-BG', 'Bulgarian'), ('cs-CZ', 'Czech'), ('da-DK', 'Danish'), ('de-DE', 'German'), ('el-GR', 'Greek'), ('en-US', 'English'), ('es-ES', 'Spanish'), ('et-EE', 'Estonian'), ('fi-FI', 'Finnish'), ('fr-FR', 'French'), ('hr-HR', 'Croatian'), ('hu-HU', 'Hungarian'), ('it-IT', 'Italian'), ('lt-LT', 'Lithuanian'), ('lv-LV', 'Latvian'), ('nl-NL', 'Dutch'), ('no-NO', 'Norwegian'), ('pl-PL', 'Polish'), ('pt-PT', 'Portuguese'), ('ro-RO', 'Romanian'), ('ru-RU', 'Russian'), ('sk-SK', 'Slovak'), ('sl-SI', 'Slovenian'), ('sv-SE', 'Swedish'), ('tr-TR', 'Turkish'), ('zh-CN', 'Chinese')], default='en-US', max_length=254, verbose_name='locale'),
        ),
    ]
